Geodjango/Geodjango/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstgis/',include('firstgis.urls',namespace="firstgis"))
]

Geodjango/firstgis/urls.py
_auther_ = 'Harry'
_date_ = '7/26/2018 9:42 PM'

from .views import HomePageView, county_dataset, point_dataset,Accessible_Entr,handi_dataset,access_entr_dataset
from django.urls import path

app_name = 'firstgis'

urlpatterns = [
    path('',HomePageView.as_view(),name='home'),
    path('county_data/',county_dataset,name="county"),
    path('incidence_data/',point_dataset,name="incidence"),
    path('campus_map/',Accessible_Entr,name="campus_map"),
    path('handi_data/',handi_dataset,name="handi_data"),
    path('access_entr_data/',access_entr_dataset,name="access_entr_data"),
]

Geodjango/firstgis/models.py
from django.db.models import Manager as GeaoManager
from django.contrib.gis.db import models

# Create your models here.
class Incidences(models.Model):
    name = models.CharField(max_length=20)
    location = models.PointField(srid=4326)
    objects = GeaoManager()

    def __int__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Incidences"  # 显示在admin中的



class Countie(models.Model):
    counties = models.CharField(max_length=25)
    codes = models.IntegerField()
    cty_code = models.CharField(max_length=24)
    dis = models.IntegerField()
    geom = models.MultiPolygonField(srid=4326)

    def __int__(self):
        return self.counties


class Accessble_Entr(models.Model):
    name = models.CharField(max_length=20)
    location = models.PointField(srid=4326)
    objects = GeaoManager()

    def __int__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Accessble Entrance"  # 显示在admin中的

class Handi_Transit(models.Model):
    name = models.CharField(max_length=20)
    location = models.PointField(srid=4326)
    objects = GeaoManager()

    def __int__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Handi Transit Stop"  # 显示在admin中的

Geodjango/firstgis/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.core.serializers import serialize
from django.http import HttpResponse
from .models import Countie,Incidences,Accessble_Entr,Handi_Transit
import json
# Create your views here.

class HomePageView(TemplateView):
    template_name = 'index.html'


class Campus_MapView(TemplateView):
    template_name = 'camples_map.html'

def county_dataset(request):
    counties = serialize('geojson',Countie.objects.all())
    return HttpResponse(counties,content_type="json")

def point_dataset(request):
    points = serialize('geojson',Incidences.objects.all())
    return HttpResponse(points,content_type="json")

def access_entr_dataset(request):
    points = serialize('geojson',Accessble_Entr.objects.all())
    return HttpResponse(points,content_type="json")

def handi_dataset(request):
    points = serialize('geojson',Handi_Transit.objects.all())
    return HttpResponse(points,content_type="json")


def Accessible_Entr(request):
    if request.method == 'POST':
        loc = request.POST['location']
        location = Incidences.objects.filter(name=loc)
        loc_json = serialize('geojson', location)
        loc_dict = json.loads(loc_json)
        loc_lat = loc_dict['features'][0]['geometry']['coordinates'][1]  # 纬度
        loc_lo = loc_dict['features'][0]['geometry']['coordinates'][0]  # 经度
        return render(request, 'camples_map.html', {
            'loc_lat': loc_lat,
            'loc_lo': loc_lo,
        })
    else:
        return render(request,'camples_map.html',{})

Geodjango/templates/camples_map.html
<!DOCTYPE html>
<html lang="en">
{% load leaflet_tags %}
{% load static %}
<head>
    <meta charset="UTF-8">
    {% leaflet_js %}
    {% leaflet_css %}

    <style type="text/css">
        #gis {width: 100%; height: 700px}
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'routing/leaflet-routing-machine.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/easy-button.css' %}">

    <script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}"></script>
    <script type="text/javascript" src="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.js' %}"></script>
    <script type="text/javascript" src="{% static 'routing/leaflet-routing-machine.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/easy-button.js' %}" ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <title>Our Home Page</title>
</head>
<body>
  <h1>Welcome to Accessible Campus!</h1>
  <form method="post" href="{% url 'firstgis:campus_map' %}">
      <h2>Your Destination:</h2><br>
      <input type="text" name="location" >
      <input type="submit">
      {% csrf_token %}
  </form>
  <script type="text/javascript">
      $("#printBtn").click(function () {
          $('#map').print();
      });
  </script>
  <br>
  <script type="text/javascript">
      function our_layers(map, options) {
          map.setView([42.30, -83.01],14);
          var osm = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
              maxZoom: 19,
              attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
          });
          var OpenTopoMap = L.tileLayer('http://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
              maxZoom: 17,
              attribution: 'Map data: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'
          });
          var datasets = new L.GeoJSON.AJAX("{% url 'firstgis:county' %}", {
              style: function colors(feature) {
                  switch (feature.properties.counties) {
                      case 'WAJIR':
                          return {
                              color: 'orange',
                              fillOpacity: 0.8
                          };
                          break;
                      case 'ISIOLO':
                          return {
                              color: 'purple',
                              fillOpacity: 0.8
                          };
                          break;

                  }
              },
              onEachFeature: function (feature, layer) {
                  layer.bindPopup(feature.properties.counties.toString());
              }

          });

          var points = new L.GeoJSON.AJAX("{% url 'firstgis:incidence' %}", {
              pointToLayer: function (feature, latlng) {
                  return L.marker(latlng, {
                      icon: L.icon({
                          iconUrl: "{% static 'img/red.png' %}",
                          iconSize: [24, 28],
                          iconAnchor: [12, 28],
                          popupAnchor: [0, -25]
                      }),
                      title: feature.properties.NAME,
                      riseOnHover: true
                  });
              },
              onEachFeature: function (feature, layer) {
                  layer.bindPopup(feature.properties.name.toString());
              }

          });

           var access_entrs = new L.GeoJSON.AJAX("{% url 'firstgis:access_entr_data' %}", {
              pointToLayer: function (feature, latlng) {
                  return L.marker(latlng, {
                      icon: L.icon({
                          iconUrl: "{% static 'img/accessible-entrance.jpg' %}",
                          iconSize: [24, 28],
                          iconAnchor: [12, 28],
                          popupAnchor: [0, -25]
                      }),
                      title: feature.properties.NAME,
                      riseOnHover: true
                  });
              },
              onEachFeature: function (feature, layer) {
                  layer.bindPopup(feature.properties.name.toString());
              }

          });
          points.addTo(map);

          var baseLayers = {
              "OSM": osm,
              "OpenTopoMap": OpenTopoMap
          }

          var groupedOverlays = {
              "Layers": {
                  "Counties": datasets,
                  "Buildings": points,
                  "Accessble Entrances":access_entrs
              }

          };

          L.control.groupedLayers(baseLayers, groupedOverlays).addTo(map);

          var routing = L.Routing.control({
              waypoints: [
                  L.latLng(42.305477, -83.065303),
                  L.latLng({{ loc_lat }}, {{ loc_lo }})
              ]
          });

          L.easyButton('fa-compass',
              function () {
                  $('.leaflet-routing-container').is(':visible') ? routing.removeFrom(map) : routing.addTo(map)
              },
              'Routing'
          ).addTo(map);


          function createButton(label, container) {
              var btn = L.DomUtil.create('button', '', container);
              btn.setAttribute('type', 'button');
              btn.innerHTML = label;
              return btn;
          }

          map.locate({setView: true, maxZoom: 16, watch: true});  // 定位
          function onLocationFound(e) {
              var radius = e.accuracy / 2;

              L.marker(e.latlng).addTo(map)
                  .bindPopup("You are within " + radius + " meters from this point").openPopup();

              L.circle(e.latlng, radius).addTo(map);
          }

          map.on('locationfound', onLocationFound);

          function onLocationError(e) {
              alert(e.message);
          }

          map.on('locationerror', onLocationError);

      }

  </script>
  {% leaflet_map "gis" callback="window.our_layers" %}
</body>
</html>

Geodjango/templates/currentlocation.html
!DOCTYPE html>
<html>
<head>
    <title>Leaflet mobile example</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />

    <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>

    <style>
        body {
        padding: 0;
        margin: 0;
        }
        html, body, #map {
        height: 100%;
    }
    </style>
</head>
<body>
<div id="map"></div>

<script>
    var map = L.map('map');

    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
            '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
            'Imagery © <a href="http://mapbox.com">Mapbox</a>',
        id: 'mapbox.streets'
    }).addTo(map);

    function onLocationFound(e) {
        var radius = e.accuracy / 2;

        L.marker(e.latlng).addTo(map)
            .bindPopup("You are within " + radius + " meters from this point").openPopup();

        L.circle(e.latlng, radius).addTo(map);
    }

    function onLocationError(e) {
        alert(e.message);
    }

    map.on('locationfound', onLocationFound);
    map.on('locationerror', onLocationError);

    map.locate({setView: true, maxZoom: 16});
    </script>
</body>
</html>

Geodjango/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load leaflet_tags %}
{% load static %}
<head>
    <meta charset="UTF-8">
    {% leaflet_js %}
    {% leaflet_css %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <style type="text/css">
        #gis {width: 80%; height: 700px}
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'routing/leaflet-routing-machine.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/easy-button.css' %}">

    <script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}"></script>
    <script type="text/javascript" src="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.js' %}"></script>
    <script type="text/javascript" src="{% static 'routing/leaflet-routing-machine.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/easy-button.js' %}" ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>


    <title>Our Home Page</title>
</head>
<body>
  <h1>Welcome to Accessible Campus!</h1>
  <script type="text/javascript">
      $("#printBtn").click(function () {
          $('#map').print();
      });
  </script>
  <br>

  <script type="text/javascript">
      function our_layers(map, options) {
          map.setView([42.30, -83.01],14);
          var osm = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
              maxZoom: 19,
              minZoom: 18,
              attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
          });
          var OpenTopoMap = L.tileLayer('http://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
              maxZoom: 17,
              attribution: 'Map data: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'
          });


          var datasets = new L.GeoJSON.AJAX("{% url 'firstgis:county' %}", {
              style: function colors(feature) {
                  switch (feature.properties.counties) {
                      case 'WAJIR':
                          return {
                              color: 'orange',
                              fillOpacity: 0.8
                          };
                          break;
                      case 'ISIOLO':
                          return {
                              color: 'purple',
                              fillOpacity: 0.8
                          };
                          break;

                  }
              },
              onEachFeature: function (feature, layer) {
                  layer.bindPopup(feature.properties.counties.toString());
              }

          });

          var points = new L.GeoJSON.AJAX("{% url 'firstgis:incidence' %}", {
              pointToLayer: function (feature, latlng) {
                  return L.marker(latlng, {
                      icon: L.icon({
                          iconUrl: "{% static 'img/red.png' %}",
                          iconSize: [24, 28],
                          iconAnchor: [12, 28],
                          popupAnchor: [0, -25]
                      }),
                      title: feature.properties.NAME,
                      riseOnHover: true
                  });
              },
              onEachFeature: function (feature, layer) {
                  layer.bindPopup(feature.properties.name.toString());
              }

          });

          //datasets.addTo(map);
          points.addTo(map);


          var baseLayers = {
              "OSM": osm,
              "OpenTopoMap": OpenTopoMap
          }

          var groupedOverlays = {
              "Layers": {
                  "counties": datasets,
                  "Buildings": points
              }

          };

          L.control.groupedLayers(baseLayers, groupedOverlays).addTo(map);



          var routing = L.Routing.control({
              waypoints: [
                  L.latLng(42.305477, -83.065303),
                  L.latLng(42.30, -83.01)
              ]
          });

          L.easyButton('fa-compass',
              function () {
                  $('.leaflet-routing-container').is(':visible') ? routing.removeFrom(map) : routing.addTo(map)
              },
              'Routing'
          ).addTo(map);


          function createButton(label, container) {
              var btn = L.DomUtil.create('button', '', container);
              btn.setAttribute('type', 'button');
              btn.innerHTML = label;
              return btn;
          }

          map.locate({setView: true, maxZoom: 16, watch: true});
          function onLocationFound(e) {
              var radius = e.accuracy / 2;

              L.marker(e.latlng).addTo(map)
                  .bindPopup("You are within " + radius + " meters from this point").openPopup();

              L.circle(e.latlng, radius).addTo(map);
          }

          map.on('locationfound', onLocationFound);

          function onLocationError(e) {
              alert(e.message);
          }

          map.on('locationerror', onLocationError);
      }

  </script>

  {% leaflet_map "gis" callback="window.our_layers" %}
</body>
</html>

Geodjango/templates/test.html
map.locate({setView: true, watch: true, maxZoom: 17})   // 定位
              .on('locationfounder',function (e) {
                  var marker = L.marker([e.latitude, e.longitude]).bindPopup('Your are here :)');
                  var circle = L.circle([e.latitude, e.longitude], e.accuracy / 2, {
                      weight: 1,
                      color: 'blue',
                      fillColor: '#cacaca',
                      fillOpacity: 0.2
                  });
                  map.addLayer(marker);
                  map.addLayer(circle);
              })
              .on('locationerror',function (e) {
                  console.log(e);
                  alert("Location access denied");
              });
          map.on('click', function (e) {  //
              alert("Lat, Lon : " + e.latlng.lat + ", " + e.latlng.lng)
          });



function onLocationFound(e) {
              var radius = e.accuracy / 2;

              L.marker(e.latlng).addTo(map)
                  .bindPopup("You are within " + radius + " meters from this point").openPopup();

              L.circle(e.latlng, radius).addTo(map);
          }

          map.on('locationfound', onLocationFound);

          function onLocationError(e) {
              alert(e.message);
          }

          map.on('locationerror', onLocationError);